spring:
  datasource:
    # 数据库用户名
    username: root
    # 数据库密码
    password: 123456
    # 数据库驱动类名，这里mysql为JDBC驱动
    driver-class-name: com.mysql.jdbc.Driver
    # 连接数据库url
    url: jdbc:mysql://127.0.0.1:3306/soremanage?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Hongkong&useAffectedRows=true
    # 数据源类型，这里使用阿里巴巴的Druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    # 数据源其他配置
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
  thymeleaf:
    cache: false
    encoding: UTF-8
  http:
    encoding:
      charset: UTF-8
mybatis:
  configuration:
    map-underscore-to-camel-case: true
server:
  port: 8080
  tomcat:
    uri-encoding: utf-8

pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true


#  stuinfosystem